spring.application.name=backend

# Server port
server.port=8080
# Aquí le decimos la dirección real de la base de datos
spring.data.mongodb.uri=mongodb://irenerossettij_db_user:ZF3hCbkzhvN5PFtg@ac-skiu3nb-shard-00-00.3osbebs.mongodb.net:27017,ac-skiu3nb-shard-00-01.3osbebs.mongodb.net:27017,ac-skiu3nb-shard-00-02.3osbebs.mongodb.net:27017/diagramador?ssl=true&replicaSet=atlas-a4964j-shard-0&authSource=admin&appName=Cluster1

jwt.secret=workflow2026SecretKeyMuyLargaParaQueSeaSegura123456789
jwt.expiration=86400000

# Logging
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.workflow.backend=DEBUG

spring.main.allow-bean-definition-overriding=true