spring.application.name=backend

# Aquí le decimos la dirección real de la base de datos
spring.data.mongodb.uri=mongodb+srv://irene_rossetti:JoseJorge__3@cluster0.egd5ary.mongodb.net/Politica_Negocio?retryWrites=true&w=majority

jwt.secret=workflow2026SecretKeyMuyLargaParaQueSeaSegura123456789
jwt.expiration=86400000