spring.application.name=backend

# Server port
server.port=8080
# Aquí le decimos la dirección real de la base de datos
spring.data.mongodb.uri=mongodb+srv://irenerossettij_db_user:ZF3hCbkzhvN5PFtg@cluster1.3osbebs.mongodb.net/diagramador?retryWrites=true&w=majority

jwt.secret=workflow2026SecretKeyMuyLargaParaQueSeaSegura123456789
jwt.expiration=86400000

# Logging
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.workflow.backend=DEBUG

spring.main.allow-bean-definition-overriding=true